=== andreamartire/lmadb/trunk/doctype.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT db_import_export (table)*>
<!ELEMENT table (row)*>
<!ELEMENT row (data)*>
<!ELEMENT data (#PCDATA)>
<!ATTLIST table name CDATA #REQUIRED>
<!ATTLIST data name CDATA #REQUIRED>
<!ATTLIST data type CDATA #REQUIRED>

=== andreamartire/lmadb/export.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root-element SYSTEM "doctype.dtd">

<db_import_export>
  <table name="sequences">
    <row>
      <data name="name" type="12">dotazioni</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">1</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">assegnazioni</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">1</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">matricole</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">8</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">allocazioni</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">7</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">richieste</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">11</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">sottoCategoriaBene</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">7</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">bando</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">2</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">SA</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">3</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">MA</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">2</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">bene</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">7</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">MB</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">2</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">stanza</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">4</data>
      <data name="cycle" type="1">F</data>
    </row>
    <row>
      <data name="name" type="12">ubicazione</data>
      <data name="startval" type="4">0</data>
      <data name="incr" type="4">1</data>
      <data name="minval" type="4">-2147483648</data>
      <data name="maxval" type="4">2147483647</data>
      <data name="currval" type="4">3</data>
      <data name="cycle" type="1">F</data>
    </row>
  </table>
  <table name="personale">
    <row>
      <data name="matricola" type="4">1</data>
      <data name="codice_fiscale" type="12">rssnnt80l14b219c</data>
      <data name="nome" type="12">Antonio</data>
      <data name="cognome" type="12">Rossi</data>
    </row>
    <row>
      <data name="matricola" type="4">2</data>
      <data name="codice_fiscale" type="12">vrdnnt75c09d122w</data>
      <data name="nome" type="12">angelo</data>
      <data name="cognome" type="12">verdi</data>
    </row>
    <row>
      <data name="matricola" type="4">3</data>
      <data name="codice_fiscale" type="12">mrtnrd88l23d122s</data>
      <data name="nome" type="12">andrea</data>
      <data name="cognome" type="12">martiro</data>
    </row>
    <row>
      <data name="matricola" type="4">4</data>
      <data name="codice_fiscale" type="12">nrelns80b19c312d</data>
      <data name="nome" type="12">alfonso</data>
      <data name="cognome" type="12">neri</data>
    </row>
    <row>
      <data name="matricola" type="4">5</data>
      <data name="codice_fiscale" type="12">bncgpp85b18c919w</data>
      <data name="nome" type="12">biagio</data>
      <data name="cognome" type="12">bianchi</data>
    </row>
    <row>
      <data name="matricola" type="4">6</data>
      <data name="codice_fiscale" type="12">lnegpp83s12c123a</data>
      <data name="nome" type="12">giuseppe</data>
      <data name="cognome" type="12">leone</data>
    </row>
    <row>
      <data name="matricola" type="4">7</data>
      <data name="codice_fiscale" type="12">gstmrt88b12c123d</data>
      <data name="nome" type="12">Umberto</data>
      <data name="cognome" type="12">Agosto</data>
    </row>
    <row>
      <data name="matricola" type="4">8</data>
      <data name="codice_fiscale" type="12">lrosvt88l96h919t</data>
      <data name="nome" type="12">salvatore</data>
      <data name="cognome" type="12">loria</data>
    </row>
  </table>
  <table name="account">
    <row>
      <data name="username" type="12">admin</data>
      <data name="password" type="12">asd</data>
      <data name="email" type="12">deadlyomen17@gmail.com</data>
      <data name="data_registrazione" type="91">2010-02-10</data>
      <data name="tipologia" type="12">amministratore</data>
      <data name="personale" type="4" />
    </row>
    <row>
      <data name="username" type="12">antonio</data>
      <data name="password" type="12">asd</data>
      <data name="email" type="12">rossi@mail.it</data>
      <data name="data_registrazione" type="91">2010-04-03</data>
      <data name="tipologia" type="12">dipendente</data>
      <data name="personale" type="4">1</data>
    </row>
    <row>
      <data name="username" type="12">verdi</data>
      <data name="password" type="12">asd</data>
      <data name="email" type="12">verdi@mail.it</data>
      <data name="data_registrazione" type="91">2010-04-03</data>
      <data name="tipologia" type="12">dipendente</data>
      <data name="personale" type="4">2</data>
    </row>
    <row>
      <data name="username" type="12">andrea</data>
      <data name="password" type="12">asd</data>
      <data name="email" type="12">andrea@mail.it</data>
      <data name="data_registrazione" type="91">2010-04-03</data>
      <data name="tipologia" type="12">dipendente</data>
      <data name="personale" type="4">3</data>
    </row>
    <row>
      <data name="username" type="12">addetto</data>
      <data name="password" type="12">asd</data>
      <data name="email" type="12">sasaloria@hotmail.com</data>
      <data name="data_registrazione" type="91">2010-04-03</data>
      <data name="tipologia" type="12">addetto amministrativo</data>
      <data name="personale" type="4">4</data>
    </row>
    <row>
      <data name="username" type="12">bianchi</data>
      <data name="password" type="12">asd</data>
      <data name="email" type="12">bianchi@mail.it</data>
      <data name="data_registrazione" type="91">2010-04-03</data>
      <data name="tipologia" type="12">dipendente</data>
      <data name="personale" type="4">5</data>
    </row>
    <row>
      <data name="username" type="12">master85</data>
      <data name="password" type="12">asd</data>
      <data name="email" type="12">leone@mail.it</data>
      <data name="data_registrazione" type="91">2010-04-03</data>
      <data name="tipologia" type="12">dipendente</data>
      <data name="personale" type="4">6</data>
    </row>
    <row>
      <data name="username" type="12">umberto</data>
      <data name="password" type="12">asd</data>
      <data name="email" type="12">zell_great@hotmail.com</data>
      <data name="data_registrazione" type="91">2010-04-03</data>
      <data name="tipologia" type="12">dipendente</data>
      <data name="personale" type="4">7</data>
    </row>
    <row>
      <data name="username" type="12">sal</data>
      <data name="password" type="12">asd</data>
      <data name="email" type="12">deadlyomen17@gmail.com</data>
      <data name="data_registrazione" type="91">2010-04-06</data>
